export const resourcetableHeader = [
  {
    name: "name",
    required: true,
    label: "Name",
    align: "left",
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "type",
    align: "left",
    label: "Type",
    field: "type",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "ipAddress",
    align: "center",
    label: "IP Address",
    field: "ipAddress",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "console",
    align: "center",
    label: "Console",
    field: "console",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "mgmtPport",
    align: "center",
    label: "MGMT Pport",
    field: "mgmtPport",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "model",
    align: "center",
    label: "Model",
    field: "model",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "aca",
    align: "center",
    label: "ACA",
    field: "aca",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "status",
    align: "center",
    label: "Status",
    field: "status",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "bookedBy",
    align: "left",
    label: "Booked by	",
    field: "bookedBy",
  },
  {
    name: "period",
    align: "center",
    label: "Period",
    field: "period",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "team",
    align: "center",
    label: "Team",
    field: "team",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
  },
  {
    name: "action",
    align: "center",
    label: "Action",
    field: "action",
  },
];
